"""Swith from psycopg2 to asyncpg

Revision ID: 5cfd4d51fd1f
Revises: e5cbf35eeb51
Create Date: 2023-04-14 12:31:52.168460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfd4d51fd1f'
down_revision = 'e5cbf35eeb51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
