"""Swith from psycopg2 to asyncpg

Revision ID: a29a83b51f7f
Revises: 5cfd4d51fd1f
Create Date: 2023-04-14 15:56:29.629701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29a83b51f7f'
down_revision = '5cfd4d51fd1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'username')
    # ### end Alembic commands ###
